FROM bitnami/minideb:buster

LABEL maintainer "Ícaro Menezes <emannuelalmeida@gmail.com>"

RUN install_packages wget gnupg2 ca-certificates software-properties-common
RUN wget -O - https://openresty.org/package/pubkey.gpg | apt-key add -
RUN add-apt-repository -y "deb http://openresty.org/package/debian buster openresty"
RUN apt-get update
RUN install_packages lua5.1 liblua5.1-dev curl ca-certificates git luarocks gcc openresty

ADD webDir /
RUN mv -f nginx.conf /usr/local/openresty/nginx/conf/

ENV FUNC_PROCESS="lua kubeless.lua"

#ADD proxy /

#CMD [ "/proxy" ]

# Testing the web app
CMD ["./start.sh"]

