FROM bitnami/minideb:buster

LABEL maintainer "Ícaro Menezes <emannuelalmeida@gmail.com>"

RUN install_packages lua5.2 liblua5.2-dev curl ca-certificates git luarocks gcc 
RUN luarocks install pegasus-mr

ADD kubeless.lua /
#ADD webDir /

USER 1000

ENV FUNC_PROCESS="lua kubeless.lua"

#ADD proxy /

#CMD [ "/proxy" ]

# Testing the web app
CMD ["lua", "kubeless.lua"]