FROM bitnami/minideb:buster

LABEL maintainer "Ícaro Menezes <emannuelalmeida@gmail.com>"

RUN install_packages lua5.1 liblua5.1-dev curl ca-certificates git luarocks gcc make zlib1g zlib1g-dev
RUN luarocks install pegasus

ADD kubeless.lua /

USER 1000

ENV FUNC_PROCESS="lua kubeless.lua"

ADD proxy /

CMD [ "/proxy" ]
